# OpenAPI specification (basic structure based off this: https://swagger.io/docs/specification/basic-structure/)
openapi: 3.0.0
info:
  title: blog-fs OpenAPI Specification
  version: 0.1.0
# Paths
paths:
  /:
    get:
      summary: Returns a hello world message.
      responses:
        '200':    # status code
          description: A hello world string
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /blogposts:
    get:
      summary: Retrieves blog posts
      responses:
        '200':
          description: All of the blog posts including content
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlogPost'
    post:
      summary: Creates a new blog post
      requestBody:
        description: This is the blog post that the client wants to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBlogPost'
      responses:
        '201':
          description: The blog post has successfully been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogPost'
              
    

# Components
components:
  schemas:
    # Schema for a single blog post
    BlogPost:
      type: object
      # list of required properties
      required:
        - author
        - title
        - publishDate
        - updatedDate
        - content

      properties:
        author:
          type: string
        title:
          type: string
        publishDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
        content:
          type: string
    # Schema for creating a new blog post
    NewBlogPost:
      type: object
      required:
        - title
        - content
      
      properties:
        title:
          type: string
        content:
          type: string
